### ISSUE TITLE
แก้เวลาคอนเทสในตอนที่คอนเทสกำลังรันอยู่ไม่ได้

### ISSUE THREAD

**Issue by Nepumi-Jr** [phakphum-dev/otog-backend#3]
ตอนแก้ เวลามันขึ้น toast ว่า Cannot PUT something นี่แหละ ซึ่งก็แก้เวลาไม่ได้
_ไม่แน่ใจว่าเป็นที่ Front หรือ Back แต่เดาว่าเปนที่ back มั้ง LMAO_

**Comment by karnjj** [comment]
Fixed
